name: cmo_driver
version: 1.0.1+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: 2.3.2
  retrofit: 4.0.1
  json_annotation: 4.8.0
  dio: 5.1.1
  logger: 1.3.0
  cached_network_image: 3.2.3
  photo_view: 0.14.0
  fluttertoast: 8.2.1
  easy_stepper: 0.5.0
  syncfusion_flutter_datepicker: 21.1.41
  intl: 0.18.1
  readmore: 2.2.0
  firebase: 9.0.3
  firebase_core: 2.10.0
  firebase_crashlytics: ^3.1.2
  firebase_analytics: 10.2.1
  dartz: 0.10.1
  octo_image: 1.0.2
  package_info_plus: 3.1.2
  flag: 6.0.0
  auto_size_text: 3.0.0
  font_awesome_flutter: 10.4.0
  get_storage: 2.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  build_runner: 2.3.3
  retrofit_generator: 6.0.0+2
  json_serializable: 6.6.1
  flutter_launcher_icons: 0.13.1
  flutter_flavorizr: 2.1.6
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/place_holder/
    - assets/staging_logo/
    - assets/images/
  fonts: 
    - family: NotoSans
      fonts: 
        - asset: fonts/NotoSans-Regular.ttf
    - family: NotoSansMyanmar
      fonts: 
        - asset: fonts/NotoSansMyanmar-Regular.ttf
  uses-material-design: true

flavorizr: 
  app: 
    android: 
      flavorDimensions: flavor-type
    ios: null
  flavors: 
    staging: 
      app: 
        name: Staging CMO Driver
      android: 
        applicationId: mm.com.cmoit.cmo_driver.staging
      ios: 
        bundleId: mm.com.cmoit.cmo_driver.staging
    prod: 
      app: 
        name: CMO Driver
      android: 
        applicationId: mm.com.cmoit.cmo_driver
      ios: 
        bundleId: mm.com.cmoit.cmo_driver

