name: CI & CD Flutter Android 

on:
  push:
    branches: [ "pre-release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
    - name: flutter build apk for Android
      run: flutter pub get
    - run: flutter build apk --release --flavor prod

    - name: Retrieve Release Version
      id: versionstep
      run: |
        VERSION=$(more pubspec.yaml | grep version: | cut -d ' ' -f2)
        echo "::set-output name=VERSION::$VERSION"
    - name: Upload the APK onto Github
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'build/app/outputs/flutter-apk/*.apk'
        token: ${{ secrets.MOBILE_GITHUB_RELEASE_UPLOAD_TOKEN }}
        tag: pre-release_${{ steps.versionstep.outputs.VERSION }}
